using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using Microsoft.EntityFrameworkCore;

using AI.Copilot.Access.Certification.Shared.Attributes;
using AI.Copilot.Access.Certification.Shared.Entities.Platform;

namespace AI.Copilot.Access.Certification.Shared.Entities.Components.Certifications;

/// <summary>
/// Stores AI-generated review recommendations for certification review items.
/// Each record represents a single AI recommendation for an employee-role pair within a campaign.
/// </summary>
[DbEntity]
[Table("AIRecommendations")]
[TableApiEntity("AIRecommendations")]
[TableChangesTrackedEntity]
public class AIRecommendation : BaseEntity, IFluentApiConfigurer
{
    /// <summary>
    /// Certification process ID linking to the parent campaign.
    /// </summary>
    [Required]
    [TableApiField]
    [TableChangesTrackedField]
    public long CertificationProcessId { get; set; }

    /// <summary>
    /// The workflow instance step ID that this recommendation targets (maps to ReviewItems.Id).
    /// </summary>
    [Required]
    [TableApiField]
    [TableChangesTrackedField]
    public long ReviewItemStepId { get; set; }

    /// <summary>
    /// The user ID of the employee being reviewed.
    /// </summary>
    [TableApiField]
    [TableChangesTrackedField]
    public long? UserId { get; set; }

    /// <summary>
    /// The role ID being evaluated.
    /// </summary>
    [TableApiField]
    [TableChangesTrackedField]
    public long? RoleId { get; set; }

    /// <summary>
    /// The system ID associated with this recommendation.
    /// </summary>
    [TableApiField]
    [TableChangesTrackedField]
    public long? SystemId { get; set; }

    /// <summary>
    /// AI recommendation decision: Approve, Reject, or Needs Review.
    /// </summary>
    [Required]
    [StringLength(20)]
    [TableApiField]
    [TableChangesTrackedField]
    public string Decision { get; set; } = null!;

    /// <summary>
    /// Confidence score of the AI recommendation (0.0 to 1.0).
    /// </summary>
    [Required]
    [TableApiField]
    [TableChangesTrackedField]
    [Column(TypeName = "decimal(5,4)")]
    public decimal ConfidenceScore { get; set; }

    /// <summary>
    /// Risk level classification: Low, Medium, High, Critical.
    /// </summary>
    [Required]
    [StringLength(20)]
    [TableApiField]
    [TableChangesTrackedField]
    public string RiskLevel { get; set; } = null!;

    /// <summary>
    /// Human-readable summary generated by the LLM explaining the recommendation rationale.
    /// </summary>
    [TableApiField]
    [TableChangesTrackedField]
    public string? RiskSummary { get; set; }

    /// <summary>
    /// Serialized JSON array of risk factors identified by the AI.
    /// Example: ["Unused for 180+ days", "SoD conflict with Finance role", "No peer usage"]
    /// </summary>
    [TableApiField]
    [TableChangesTrackedField]
    public string? RiskFactors { get; set; }

    /// <summary>
    /// Usage percentage of the role at the time of analysis.
    /// </summary>
    [TableApiField]
    [TableChangesTrackedField]
    public long? UsagePercentage { get; set; }

    /// <summary>
    /// Number of days since the role was last used. Null if never used.
    /// </summary>
    [TableApiField]
    [TableChangesTrackedField]
    public int? DaysSinceLastUsed { get; set; }

    /// <summary>
    /// Whether an SoD (Separation of Duties) violation was detected for this role assignment.
    /// </summary>
    [TableApiField]
    [TableChangesTrackedField]
    public bool HasSodViolation { get; set; }

    /// <summary>
    /// Percentage of peers in the same department/job who also have this role.
    /// </summary>
    [TableApiField]
    [TableChangesTrackedField]
    [Column(TypeName = "decimal(5,2)")]
    public decimal? PeerUsagePercent { get; set; }

    /// <summary>
    /// Whether the role was flagged as an anomaly based on embedding comparison.
    /// </summary>
    [TableApiField]
    [TableChangesTrackedField]
    public bool IsAnomaly { get; set; }

    /// <summary>
    /// Anomaly score from the embedding-based detector (0.0 to 1.0). Higher = more anomalous.
    /// </summary>
    [TableApiField]
    [TableChangesTrackedField]
    [Column(TypeName = "decimal(5,4)")]
    public decimal? AnomalyScore { get; set; }

    /// <summary>
    /// The version of the AI model used to generate this recommendation.
    /// </summary>
    [StringLength(50)]
    [TableApiField]
    [TableChangesTrackedField]
    public string? ModelVersion { get; set; }

    /// <summary>
    /// Prompt template version used for this recommendation.
    /// </summary>
    [StringLength(50)]
    [TableApiField]
    [TableChangesTrackedField]
    public string? PromptVersion { get; set; }

    /// <summary>
    /// Token count consumed by the LLM call for this recommendation.
    /// </summary>
    [TableApiField]
    [TableChangesTrackedField]
    public int? TokensUsed { get; set; }

    /// <summary>
    /// Processing time in milliseconds for generating this recommendation.
    /// </summary>
    [TableApiField]
    [TableChangesTrackedField]
    public int? ProcessingTimeMs { get; set; }

    /// <summary>
    /// Status of the recommendation: Pending, Generated, Failed, Expired.
    /// </summary>
    [Required]
    [StringLength(20)]
    [TableApiField]
    [TableChangesTrackedField]
    public string Status { get; set; } = "Pending";

    /// <summary>
    /// Error message if the recommendation generation failed.
    /// </summary>
    [StringLength(2000)]
    [TableApiField]
    public string? ErrorMessage { get; set; }

    /// <summary>
    /// Timestamp when the recommendation was generated.
    /// </summary>
    [TableApiField]
    [TableChangesTrackedField]
    public DateTimeOffset? GeneratedAt { get; set; }

    /// <summary>
    /// Navigation to feedback entries for this recommendation.
    /// </summary>
    [TableApiNavigation]
    public ICollection<AIRecommendationFeedback> Feedbacks { get; set; } = [];

    public void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AIRecommendation>(entity =>
        {
            entity.HasIndex(e => new { e.CertificationProcessId, e.ReviewItemStepId })
                .IsUnique()
                .HasDatabaseName("IX_AIRecommendations_Campaign_Step");

            entity.HasIndex(e => e.CertificationProcessId)
                .HasDatabaseName("IX_AIRecommendations_Campaign");

            entity.HasIndex(e => new { e.CertificationProcessId, e.Decision })
                .HasDatabaseName("IX_AIRecommendations_Campaign_Decision");

            entity.HasIndex(e => e.Status)
                .HasDatabaseName("IX_AIRecommendations_Status");
        });
    }
}
